### ISSUE TITLE
[Feature] Jei integration

### ISSUE THREAD

**Issue by novaexe** [FTBTeam/FTB-GUI-Library#1]
JEI has an API to allow other mods to tell JEI where they draw, so that JEI doesnt overlap with it

**Comment by EddwardR** [comment]
Definitely worth implementing. Currently the FTB buttons are over the bookmarked items of JEI. This makes the first item real annoying to click.
![image](https://user-images.githubusercontent.com/20886040/92119947-1a30b880-ee01-11ea-8d3c-c8ba111f1d29.png)

**Comment by MaxNeedsSnacks** [comment]
Should be fixed in newer releases
