### ISSUE TITLE
Ftbguilibrary error

### ISSUE THREAD

**Issue by blarghhh** [FTBTeam/FTB-GUI-Library#12]
version: ftb-gui-library-1604.2.0.30-forge. jar

in game on a server, i am an op. when i try to click the change to day time, it gives me an error.

Unknown or incomplete command, see below for error
/ftbguilibrary gamemode<--[HERE]

**Comment by SalmonSays** [comment]
Came here to check this is known, I'm having the same problem

**Comment by martymarty004** [comment]
same problem

**Comment by mindcloud69** [comment]
Same issue here. No error other than unknown command in the logs
ftb-gui-library-1604.2.0.30-forge
forge-1.16.4-35.1.36

**Comment by UmJammerSully** [comment]
Yep, same issue. Been troubleshooting this for hours, still not sure what is causing it.

**Comment by wazzasay** [comment]
Yup same issue with FTB Chunks and guilib, 

forge-1.16.4

**Comment by blarghhh** [comment]
update: in singleplayer survival, there is no problem. i can change the time with no errors

**Comment by martymarty004** [comment]
Update: I updated my client/server to the latest version of Forge and FTBGui and the issue disappeared

**Comment by Drakonas** [comment]
This issue has crept back up again. See issue #25
