### ISSUE TITLE
FTB GUI Library requiring Architectury?

### ISSUE THREAD

**Issue by drfleetles** [FTBTeam/FTB-GUI-Library#16]
This mod, plus Ftb Teams cannot be loaded because this other mod "Architectury" is not installed. I search it up but it doesn't 
exist

here are the details 
Mod File: ftb-gui-library-1605.2.1.37-forge.jar
	Failure message: Mod ftbguilibrary requires architectury 1.1.53 or above
		Currently, architectury is not installed
	Mod Version: 1605.2.1.37
	Mod Issue URL: https://github.com/FTBTeam/FTB-GUI-Library/issues
	Exception message: MISSING EXCEPTION MESSAGE

here is the full crash report
[crash-2021-01-31_12.20.46-fml.txt](https://github.com/FTBTeam/FTB-GUI-Library/files/5899057/crash-2021-01-31_12.20.46-fml.txt)

**Comment by MatthewWeyer** [comment]
check relations on curseforge, archictectury will show up there

**Comment by drfleetles** [comment]
i see, thank you. But the annoying thing was that it wasnt searchable. like i couldnt search it on google

**Comment by MatthewWeyer** [comment]
It actually is searchable, devs just chose a bad name for the mod. If you search architectury minecraft, google will think you meant architecture, and give you a million and one search results concerning that. It is actually the second result, (below the fabric version of architectury) if you search "Minecraft architectury API mod"
