### ISSUE TITLE
FTB GUI Library has failed to load properly - Error when launching MC

### ISSUE THREAD

**Issue by KitKatPanda** [FTBTeam/FTB-GUI-Library#18]
I'm trying to run a modded mc, with a mod list I put together. I was able to play fine, then realized I needed FTBguiLib and added it, then my game crashed when loading. 

The main error I'm getting is **java.lang.NoClassDefFoundError: me/shedaniel/architectury/utils/Env**

Here is the error log I'm receiving; I would greatly appreciate any help that can be given

https://pastebin.com/5UGSK9Um

**Comment by MaxNeedsSnacks** [comment]
Shouldn't be an issue anymore if you have the latest Architectury API installed
