### ISSUE TITLE
FTB Teams icons not showing up

### ISSUE THREAD

**Issue by VenoVenice** [FTBTeam/FTB-GUI-Library#19]
I have installed both FTB GUI and FTB Teams, but icons for teams are not showing up.

**Comment by storiofmylife** [comment]
I'm having the same problem myself. Tried without OptiFine and still only see none for Teams.

**Comment by MaxNeedsSnacks** [comment]
FTB Teams does not have GUI support yet as the 1.16 version is **very** early in development
