### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by PeHeReBe** [FTBTeam/FTB-GUI-Library#23]
symbol:   class Image
  location: interface ImageCallback
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:compileJava'.

    Compilation failed; see the compiler error output for details.

images and icons cant be found by gradle

**Comment by MaxNeedsSnacks** [comment]
You're missing JavaFX on your classpath, which (as of now) is still being used by FTB GUI Library. You can fix this by setting your JDK to Java 8 or adding it to the classpath yourself
