### ISSUE TITLE
[1.16.3] Rendering screen crash

### ISSUE THREAD

**Issue by bookerthegeek** [FTBTeam/FTB-GUI-Library#4]
### HEYO! ###

Was running your mod and got a crash to desktop.
#### Stuff ####
[Crash Report - Client](https://gist.github.com/bookerthegeek/bb692f6ccd6e431595b76a039ac5a8b0)
[Crash Report - FML](https://gist.github.com/bookerthegeek/42bd9c4ae2c8f7f780b9d0385ef7983d)

#### Other Stuff ####
This happened when when I tried to close the world map. The mod list is in the report.

~ EDIT ~
I also get this crash when trying to modify JEI settings, such as centering the search bar.

###### Oh well, six one way and half a dozen the other I guess. ######

**Comment by Anteater46** [comment]
Getting the same crash, tried earlier versions of GUI-Library with the same result.

**Comment by Anteater46** [comment]
This is fixed already btw @bookerthegeek  :)

**Comment by bookerthegeek** [comment]
@Anteater46 Awesome! Is the fixed version up on Curse yet?

**Comment by Anteater46** [comment]
@bookerthegeek Yep! This was fixed specifially in GUI Lib 1.1.22/23 but the latest version should work fine :)
